# This is a basic workflow to help you get started with Actions

name: NotionJAM

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 21 * * *" # daily
  push:
    branches: [master, main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: notion-jam
        uses: victornpb/notion-jam@v0.0.13
        with:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          NOTION_DATABASE: https://www.notion.so/1bfcc14e575580929349e3f039bb532c
          FILTER_PROP: Status
          FILTER_VALUES: Published
          CONVERT_PROP_CASE: snake
          ARTICLE_PATH: content/writing/{title}.md
          ASSETS_PATH: static/images/
          PARALLEL_PAGES: 25
          PARALLEL_DOWNLOADS_PER_PAGE: 3
          DOWNLOAD_IMAGE_TIMEOUT: 30
          SKIP_DOWNLOADED_IMAGES: false
          DOWNLOAD_FRONTMATTER_IMAGES: true
      
      - name: Save changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit changes
